version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
      - .pg_hba.conf:/etc/postgresql/12/main/pg_hba.conf
  web:
    build:
      context: .
    image: spina:dev
    env_file:
      - .env
    volumes: 
      - .:/ror
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://rails:postgres@database:5432/spina_db      
      RAILS_ENV: development
    depends_on:
      - database
  web-prod:
    build:
      context: .
    image: spina:prod
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
    profiles:
      - stopped
